name: Integration tests

on:
  push:
    branches:
      - develop

env:
  SLACK_CHANNEL: integration
  SLACK_USERNAME: slackbot
  SLACK_ICON: https://github.githubassets.com/images/icons/emoji/unicode/1f916.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  MSG_MINIMAL: ref,actions url

jobs:
  test:
    name: Integration tests
    runs-on: self-hosted

    strategy:
      matrix:
        flavors:
          - name: sonic
            env: MINI_LAB_FLAVOR=sonic
          - name: cumulus
            env: MINI_LAB_FLAVOR=cumulus

    steps:
    - name: Gain back workspace permissions # https://github.com/actions/checkout/issues/211
      run: |
        [ -d "${GITHUB_WORKSPACE}" ] && sudo chown -R $USER:$USER ${GITHUB_WORKSPACE}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Run integration tests
      shell: bash
      run: |
        export TMPDIR=/var/tmp/
        ./test/integration/ci-prep.sh
        make wait-for-images
        make integration-deployment
        make integration-ansible-modules
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: test/integration/**/output/*.xml
      if: ${{ matrix.flavors.name == 'sonic' }}

    - name: Slack Notification on Success
      uses: rtCamp/action-slack-notify@v2
      # this step is sometimes flaky... :(
      continue-on-error: true
      env:
        SLACK_COLOR: good
        SLACK_TITLE: 'Integration Tests succeeded'
      if: ${{ matrix.flavors.name == 'sonic' && success() }}

    - name: Slack Notification on Failure
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: red
        SLACK_TITLE: 'Integration Tests failed'
      if: ${{ matrix.flavors.name == 'sonic' && failure() }}
