name: Integration tests

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Integration tests
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run integration tests
      shell: bash
      run: |
        ./test/integration/ci-prep.sh
        make integration-deployment
        make integration-ansible-modules
