name: Integration tests

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Integration tests
    runs-on: self-hosted
    steps:
    - name: Cleanup steps from prior runs
      shell: bash
      run: |
        sudo chown -R $USER:$USER /var/lib/gitlab-runner/github/_work/releases
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run integration tests
      shell: bash
      run: |
        export TMPDIR=/var/tmp/
        ./test/integration/ci-prep.sh
        make wait-for-docker-images
        make integration-deployment
        make integration-ansible-modules
