name: Publish OCI Artifact

on:
  pull_request:
    branches:
      - master
      - develop
  release:
    types:
      - published
  push:
    branches:
      - master
    tags-ignore:
      # this is handled by release publish trigger
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  oci-release-vector:
    uses: metal-stack/actions-common/.github/workflows/oci-release-vector-artifact.yaml@v1
    secrets: inherit
    with:
      artifact-type: release-vector
