name: Publish OCI Artifact

on:
  pull_request:
    branches:
      - master
  release:
    types:
      - published
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  oci-artifact:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Make tag
      run: |
        [ "${GITHUB_EVENT_NAME}" == 'pull_request' ] && echo "tag=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV || true
        [ "${GITHUB_EVENT_NAME}" == 'release' ] && echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV || true
        [ "${GITHUB_EVENT_NAME}" == 'push' ] && echo "tag=latest" >> $GITHUB_ENV || true

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Oras
      uses: oras-project/setup-oras@v1

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3

    - name: Publish and sign
      run: |
        tar -czvf release.tar.gz release.yaml

        digest=$(oras push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.tag }} \
            --artifact-type application/vnd.metal-stack.release-vector.v1 \
            release.tar.gz:application/vnd.metal-stack.release-vector.v1.tar+gzip \
            --format go-template \
            --template "{{ .digest }}")

        cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.tag }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${digest}
